version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    ports:
      - "10034:10034"
  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    ports:
      - "10033:10033"

